
paths:
  /api/products:
    get:
      summary: Retorna la lista completa de Productos
      tags:
        - Productos
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        "500":
          description: 'ERROR'

    post:
      summary: Recibe un body para crear un producto
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              # Esta referencia permite indicar la lista de campos que se deberían
              # enviar en el body al contactar a este endpoint (ver requestBodies más abajo)
              $ref: '#/components/requestBodies/Products'
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        "500":
          description: 'ERROR'


  /api/products/{pid}:

    get:
      summary: Retorna los detalles del producto especificado
      tags:
        - Productos

      parameters:
        - name: pid
          in: path
          required: false
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        "500":
          description: 'ERROR'
    
    put:
      summary: Recibe un body para modificar un producto
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/requestBodies/Products'
            example:
              Title: "Ejemplo de Producto"
              Description: "Descripción de ejemplo"
              Code: 12345
              Price: 99.99
              Status: true
              Stock: 10
              Category: "Ejemplo de Categoría"
              Thumbnail: []
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        "500":
          description: 'ERROR'
    
    delete:
      summary: Borra el prodcuto con el id indicado
      tags:
        - Productos
      parameters:
        - name: pid
          in: path
          required: true
          description: Mongoose ObjectID
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        "500":
          description: 'ERROR'

  /api/productsowned:

    get:
      summary: Retorna la lista de Productos de un usuario Premium
      tags:
        - Productos
      responses:
        "200":
          description: 'OK'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Products'
        "500":
          description: 'ERROR'
    

components:
  schemas:
    Products:
      type: object
      properties:
        _id:
          type: object
          description: Mongoose ObjectID
        Title:
          type: string
        Description:
          type: string
        Code:
          type: number
        Price:
          type: number
        Status:
          type: Boolean
        Stock:
          type: number
        Category:
          type: string
        Thumbnail:
          type: array


  requestBodies:
    Products:
      type: object
      properties:
        Title:
          type: string
        Description:
          type: string
        Code:
          type: number
        Price:
          type: number
        Status:
          type: Boolean
        Stock:
          type: number
        Category:
          type: string
        Thumbnail:
          type: array